---
title: A toy model for supply and demand
author: Pablo Barbancho Martín
date: '2021-04-01'
slug: a-toy-model-for-supply-and-demand
categories:
  - Economy
tags:
  - Supply and demand
subtitle: ''
summary: ''
authors: []
lastmod: '2021-04-02T00:41:59+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
A toy model for supply and demand is derived from the knowledge of the probability distribution for the prices that different agents consider fair for a certain good. The model obtained shows the expected characteristics of supply and demand curves and allows further development in market dynamics.

# Statement of the problem

We want to model the collective behaviour of a set of agents that participate in the buying and selling of a certain good. Each of these agents will buy or sell depending on whether the price reached by the good in question is a price they consider fair or not. Besides, this quantity does not have to be unique, depending on this price they may decide to buy or sell a larger or smaller quantity. Considering, for example, a seller agent, this follows a scheme such as this.

Such an agent will decide to supply an amount of $c_1$ if the good reaches a price of $p_1$, an amount of $c_2$ if it reaches a price of $p_2$ and so on. If we call $\lim_{i \rightarrow \infty} c_i = M$ and assuming that the higher the price, the greater the quantity supplied (law of supply), we can write the supply function as

$$o(p) = \sum_{i = 1} ^ M \theta (p-p_i),\tag{1}$$ 

where $\theta(x)$ is the Heaviside step function given by

$$\theta(x)=\left\{
    \begin{array}{rr}
    0, & \text{if } x <0  \\ 
    1, & \text{if } x \geq 0 
    \end{array}
    \right..
\tag{2}
$$ 

In the case of a buyer agent, and taking into account the law of demand, it is only needed to change the sign of the argument of the Heaviside function to obtain

$$d(p)=\sum_{i = 1}^M\theta(p_i-p).\tag{3}$$ 

With that said, our objective is, discarding the possibility of knowing the $p_i$ for all the participating agents, to obtain some functions $O (p)$ and $D (p)$ that describe the collective behaviour of the agents selling and buying, respectively, from the knowledge of the probability distribution of the $p_i$.

# Previous assumptions

In the first place, we are going to assume a number $N_o$ of agents that sell the good under study, as well as a number $N_d$ of agents that buy that same good. Besides, we assume the knowledge of the probability distributions $P_o (p_i)$ and $P_d (p_i)$ of the $p_i$ of both sellers and buyers as groups. 

We will also assume that the agents do not interact with each other, that is, there is no correlation between the quantities supplied (demanded) by the different agents.

Finally, we will assume that a specific agent, given that at a particular price has sold (bought) a unit of the good, there is a probability $q_i$ that it will sell (buy) an additional unit and that this remains constant as we increase. the quantity supplied (demanded).

# The supply case

Let's start by dealing with the case of the offer. Given the functions $o_i (p)$ of each of the selling agents, total or aggregate supply will be given by

$$O(p) = \sum_ {i = 1} ^ {N_o} o_i (p).\tag{4}$$ 

If we stop to think about the nature of prices $p$, they represent the conversion factor, in terms of value, between a certain good and another that we consider as a standard. Therefore we will have $p \in \mathbb{Q}$. But it is a known result that $\mathbb{Q}$ is a countable set, so we can put $\mathbb{Q}$ in one-to-one correspondence with $\mathbb{N}$. Let's say that we establish this correspondence through $\phi: \mathbb{Q} \rightarrow \mathbb{N}$. In this way, we are going to make a variable change, and we are going to study supply as a function of $n = \phi (p)$, having $p = \phi^{- 1} (n)$.

Thus, we will have a new set of functions $\omega_i (n) = o_i \circ \phi ^ {- 1} (n)$, as well as a new probability distribution $\Pi_o (n_i) = P_o \circ \phi ^ {-1} (n_i)$, where $n_i = \phi (p_i)$. Similarly, the aggregate supply will be represented by

$$\Omega (n) = \sum ^ {N_o} _ {i = 1} \omega_i (n).\tag{5}$$ 

Remembering how we define the $o_i (p)$ from the Heaviside step function, we have

$$\omega_i (n) = \sum_ {j = 1} ^ {m_i} \theta (\phi ^ {- 1} (n) - \phi ^ {- 1} (n_ {ij})),\tag{6}$$ 

where $n_{ij} = \phi (p_{ij})$. But since $\phi$ is a bijection, we will have $\phi^{- 1} (n) = \phi^{- 1} (n_{ij})$, which implies that $n = n_ {ij}$, and therefore we can rewrite (6) as

$$ \omega_i (n) = \sum_ {j = 1} ^ {m_i} \theta (n-n_ {ij}).\tag{7}$$ 

However, knowing the $m_i$ of each of the agents that negotiate in the market seems like a vast task in the first instance. For this reason, we are going to lower our level of knowledge about the agents and we are going to assume that each of them has a probability $q_i$ of selling an additional unit and that this remains constant as we increase the quantity supplied.

Thus, we are going to define a function $\bar \omega_i (n)$ that will be given by

$$ \bar \omega_i (n) = \sum_ {j = 0} ^ \infty (q_i) ^ j \theta (n-n_ {ij}),\tag{8}$$ 

through which we also define

$$ \bar \Omega (n) = \sum_ {i = 1} ^ {N_o} \bar \omega_i (n),\tag{9}$$ 

and we are going to establish, with no proof, that $\lim_{N_o \rightarrow \infty} \bar \Omega (n) = \Omega (n)$. Thus, when $N_o$ is large enough, studying $\bar \Omega (n)$ will be almost equivalent to studying $\Omega (n)$, and in particular $\langle \bar \Omega (n) \rangle = \langle \Omega (n) \rangle$.

Until now, implicitly, we have assumed that the $p_ {ij}$ (and consequently the $n_ {ij}$) are known, but the only thing we know is their probability distribution. Therefore, we are going to average $\bar \Omega (n)$ to eliminate this dependency on the $n_ {ij}$. Since we have assumed that agents do not interact with each other, we will have

$$ \langle \bar \Omega (n) \rangle = \sum_ {i = 1} ^ {N_o} \langle \bar \omega_i (n) \rangle.\tag{10}$$ 

Thus, taking (7) into account, we will have

$$
\begin{aligned} 
\langle \bar \omega_i (n) \rangle & = & \sum_ {j = 0} ^ \infty (q_i) ^ j \langle \theta (n-n_ {ij})\rangle, 
\\ & = & \sum_ {j = 0} ^ \infty (q_i) ^ j \sum_ {n_ {ij}} \theta (n-n_ {ij}) \Pi_o (n_ {ij}), \\ 
\end{aligned} 
\tag {11}
$$ 

and since in general $n_ {ij} \in [0, \infty)$, we will have $\sum_ {n_ {ij}} \theta (n-n_ {ij}) \Pi_o (n_ {ij}) = \sum_ {k = 0} ^ \infty \theta (n-k) \Pi_o (k)$, but taking into account the definition of the step function, we will have $\sum_ {k = 0} ^ \infty \theta (n-k ) \Pi_o (k) = \sum_ {k = 0} ^ n \Pi_o (k)$. In this way, we will have that (11) becomes

$$\langle \bar \omega_i (n) \rangle = (\sum_ {j = 0} ^ \infty (q_i) ^ j) (\sum_ {k = 0} ^ n \Pi_o (k)).\tag{12}$$ 

Since $q_i$ represents a probability, it will take values between 0 and 1. Disregarding the case $q_i = 1$ we will have a geometric series of ratio $q_i$, so (11) is equivalent to

$$\langle \bar \omega_i (n) \rangle = \dfrac {\sum_ {k = 0} ^ n \Pi_o (k)} {1-q_i},\tag{13}$$ 

that introduced in (9) leads us to

$$\langle\bar \Omega (n) \rangle = Q (N_o, \{q_i \}) \varphi_o (n),\tag{14}$$ 

where $Q (N_o, \{q_i \}) = \sum_ {i = 1} ^ {N_o} \frac{1}{1-q_i}$, whose minimum value is $N_o$ for the case in which all the $q_i$ are equal to 0 and tends to infinity when any of the $q_i$ goes to 1, and $\varphi_o (n) = \sum_ {k = 0} ^ n \Pi_o (k)$, which tends to 0 when $n$ goes to 0, and goes to 1 when $n$ goes to infinity.

# The demand case

Having dealt with the case of supply, the case of demand is trivial. The only substantial difference is in $\varphi_d (n)$, which in this case will be equal to

$$\varphi_d(n) = \sum_ {k = n} ^ \infty \Pi_d (k),\tag{15}$$ 

where we see that it tends to 1 as $n$ has 0 and 0 as $n$ tends to infinity. We get like this

$$\langle \bar \Delta (n) \rangle = Q (N_d, \{q_i \}) \varphi_d (n).\tag{16}$$ 

# Conclusion

We have been able to obtain a model that describes the general characteristics of supply and demand. Although this depends to a large extent on the probability distribution assigned to the $p_i$, it constitutes a powerful framework when it comes to research the behaviour of collective supply and demand in a given market, as well as in the dynamics that are derived that market from these. In future publications, we will obtain the supply and demand curves that derive from different probability distributions.